### ISSUE TITLE
How to cite? 

### ISSUE THREAD

**Issue by NielsHygum** [roboscienceorg/veranda#18]
**Is your feature request related to a problem? Please describe.**
We want to write a conference paper where we have used Veranda to simulate our robot in 2D. How do you want to be cited? 

**Describe the solution you'd like**
bibtex code could be nice

**Comment by Ipiano** [comment]
How does this look?
```
 @software{veranda,
  author = {{Kendra Diezel, Jeff McGough, Chris Smith, Andrew Stelter, Riley Sutton, Samuel Williams.}},
  title = {Veranda},
  url = {https://github.com/roboscienceorg/veranda},
  version = {1.0},
  date = {Jan. 2019},
} 
```

**Comment by NielsHygum** [comment]
The bibtex style used by the conference paper did not show the url field so I changed it to
```
@software{veranda,
  author = {{Kendra Diezel, Jeff McGough, Chris Smith, Andrew Stelter, Riley Sutton, Samuel Williams.}},
  title = {Veranda},
  howpublished={\url{https://github.com/roboscienceorg/veranda}},
  version = {1.0},
  date = {Jan. 2019},
}
```

**Comment by Ipiano** [comment]
That is fine, thank you for the update
